services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
  frontend:
    build:
      context: ./frontend/app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
