site_name: Tanker24

# Repository
repo_name: SQS-THRO/Tanker24
repo_url: https://github.com/SQS-THRO/Tanker24

# Copyright
copyright: Copyright &copy; 2026 SQS Team 3

theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-2
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon:
    assets/favicon.svg
  logo: assets/favicon.svg

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

# Page tree
nav:
  - Home:
    - index.md
    - Entity-Relationship model: er-model.md
    - Class model: class-model.md
  - Getting started:
    - Installation: installation.md
    - Usage: usage.md
  - ADRs:
    - decisions/index.md
    - decisions/ADR_001_FastAPI.md
    - decisions/ADR_002_fastapi-users.md
    - decisions/ADR_003_Svelte.md
    - decisions/ADR_004_Postgresql.md
  - arc42:
    - arc42.md
    - arc42/01_intro_goals.md
    - arc42/02_constraints.md
    - arc42/03_context_scope.md
    - arc42/04_solution_strategy.md
    - arc42/05_building_block_view.md
    - arc42/06_runtime_view.md
    - arc42/07_deployment_view.md
    - arc42/08_crosscutting_concepts.md
    - arc42/09_architecture_decisions.md
    - arc42/10_quality.md
    - arc42/11_risks_technical_debt.md
    - arc42/12_glossary.md


