sonar.projectKey=SQS-THRO_Tanker24
sonar.organization=sqs-thro

sonar.sources=frontend/app/src,backend/app
sonar.coverage.exclusions=frontend/app/**/*.test.*,frontend/app/**/*.e2e.*
sonar.cpd.exclusions=frontend/app/src/lib/i18n/*.ts,frontend/app/**/*.test.*
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=frontend/app/coverage/lcov.info
sonar.python.coverage.reportPaths=backend/coverage.xml

sonar.sourceEncoding=UTF-8

sonar.issue.ignore.multicriteria=e1

sonar.issue.ignore.multicriteria.e1.ruleKey=python:S8409
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.py
