sonar.projectKey=SQS-THRO_Tanker24
sonar.organization=sqs-thro

sonar.sources=frontend/app/src,backend/app
sonar.tests=frontend/app/src,backend/tests
sonar.coverage.javascript.lcovReportPaths=frontend/app/coverage/lcov.info
sonar.coverage.python.reportPaths=backend/coverage.xml

sonar.sourceEncoding=UTF-8
